Repository bcgov/sso-realm-registry, pull requests merged in 2023-11, with the labels that each got.

#117 feat: initial backend implementation for custom realm request
  .github/workflows/lint-pr.yml
  .tool-versions
  app/.env.example
  app/Dockerfile
  app/Makefile
  app/README.md
  app/next.config.js
  app/package.json
  app/page-partials/my-dashboard/RealmEdit.tsx
  app/page-partials/my-dashboard/RealmTable.tsx
  app/pages/api/events.ts
  app/pages/api/meta/ministry.ts
  app/pages/api/realms.ts
  app/pages/api/realms/[id].ts
  app/pages/api/realms/all.ts
  app/pages/api/realms/one.ts
  app/pages/api/realms/pending.ts
  app/prisma/schema.prisma
  app/requirements.txt
  app/services/realm.ts
  app/utils/ches.ts
  app/utils/github.ts
  app/utils/helpers.ts
  app/utils/prisma.ts
  app/utils/terraform.ts
  app/utils/tf-custom-realm-template.mustache
  app/validators/create-realm.ts
  app/yarn.lock
  helm/webapp/Chart.yaml
  helm/webapp/migration.sql
  helm/webapp/templates/deployment.yaml
  helm/webapp/values-c6af30-dev.yaml
  helm/webapp/values-c6af30-prod.yaml
Labels: enhancement

#118 feat: pass github environment variables from vault
  helm/webapp/templates/deployment.yaml
  helm/webapp/values-c6af30-dev.yaml
  helm/webapp/values-c6af30-prod.yaml
Labels: enhancement

#119 feat: add user and assign realm admin permissions
  CODEOWNERS
  app/.env.example
  app/controllers/keycloak.ts
  app/next.config.js
  app/pages/api/bceid-service/bceid.ts
  app/pages/api/bceid-service/idir.ts
  app/pages/api/realms/pending.ts
  app/utils/idir.ts
  app/validators/create-realm.ts
  helm/webapp/templates/deployment.yaml
Labels: enhancement

#116 feat: realm request ui
  .github/workflows/test.yml
  app/.env.example
  app/__tests__/custom-realm-dashboard.test.tsx
  app/__tests__/custom-realm-form.test.tsx
  app/components/Modal.tsx
  app/context/modal.ts
  app/jest.config.js
  app/jest.setup.js
  app/layout/Layout.tsx
  app/package.json
  app/page-partials/custom-realm-dashboard/CustomRealmTabs.tsx
  app/pages/_app.tsx
  app/pages/api/realms.ts
  app/pages/custom-realm-dashboard.tsx
  app/pages/custom-realm-form.tsx
  app/pages/index.tsx
  app/services/realm.ts
  app/svg/IntroRealms.tsx
  app/types/realm-profile.ts
  app/utils/helpers.ts
  app/validators/create-realm.ts
  app/yarn.lock
Labels: enhancement

#121 fix: build
  app/page-partials/my-dashboard/RealmEdit.tsx
  app/page-partials/my-dashboard/RealmTable.tsx
  app/pages/custom-realm-form.tsx
  app/types/realm-profile.ts
Labels: bug

#122 fix(dockerfile): copy custom realm terraform template to container
  app/Dockerfile
Labels: bug

#123 fix: type
  app/pages/my-dashboard.tsx
Labels: bug

#124 fix: validation schema for plan and apply
  app/validators/create-realm.ts
Labels: bug

#125 fix: email
  app/utils/mailer.ts
Labels: bug

#126 feat: add events
  app/__tests__/custom-realm-dashboard.test.tsx
  app/page-partials/custom-realm-dashboard/CustomRealmTabs.tsx
  app/pages/custom-realm-form.tsx
  app/services/events.ts
  app/types/event.ts
Labels: enhancement

#128 chore: emails
  app/pages/api/realms.ts
  app/pages/api/realms/[id].ts
  app/utils/mailer.ts
Labels: enhancement

#127 feat: form update
  app/__tests__/api/update-realm.test.ts
  app/__tests__/custom-realm-dashboard.test.tsx
  app/__tests__/custom-realm-form.test.tsx
  app/__tests__/fixtures.ts
  app/__tests__/my-dashboard.test.tsx
  app/components/InfoPopover.tsx
  app/components/RealmForm.tsx
  app/jest.config.js
  app/package.json
  app/page-partials/custom-realm-dashboard/CustomRealmTabs.tsx
  app/page-partials/my-dashboard/RealmEdit.tsx
  app/page-partials/my-dashboard/RealmRightPanel.tsx
  app/page-partials/my-dashboard/RealmTable.tsx
  app/pages/custom-realm-form.tsx
  app/services/meta.ts
  app/singleton.ts
  app/types/realm-profile.ts
  app/validators/create-realm.ts
  app/yarn.lock
Labels: enhancement

#129 feat: enable the created user
  app/controllers/keycloak.ts
Labels: enhancement

#130 chore: form updates
  app/__tests__/custom-realm-form.test.tsx
  app/components/RealmForm.tsx
  app/page-partials/my-dashboard/RealmEdit.tsx
  app/validators/create-realm.ts
Labels: bug, enhancement

#131 fix: others
  app/components/RealmForm.tsx
  app/types/realm-profile.ts
Labels: bug

#133 chore: update emails
  app/utils/mailer.ts
Labels: enhancement

#134 fix: env
  app/utils/mailer.ts
Labels: bug
