Repository bcgov/sso-realm-registry, pull requests merged in 2023-12, with the labels that each got.

#136 fix: update realm info after approved and applied
  app/.env.example
  app/__tests__/custom-realm-form.test.tsx
  app/__tests__/my-dashboard.test.tsx
  app/components/RealmForm.tsx
  app/controllers/msal.ts
  app/next.config.js
  app/package.json
  app/page-partials/my-dashboard/RealmIDIR.tsx
  app/page-partials/my-dashboard/RealmURIs.tsx
  app/pages/api/azure-service/idir-user.ts
  app/pages/api/azure-service/idir-users.ts
  app/pages/api/realms.ts
  app/pages/api/realms/[id].ts
  app/pages/api/realms/pending.ts
  app/pages/custom-realm-dashboard.tsx
  app/services/azure.ts
  app/types/realm-profile.ts
  app/utils/helpers.ts
  app/validators/create-realm.ts
  app/yarn.lock
  helm/webapp/Chart.yaml
  helm/webapp/templates/deployment.yaml
Labels: bug, enhancement

#138 feat: allow realm deletion
  app/__tests__/api/delete-realm.test.ts
  app/controllers/keycloak.ts
  app/pages/api/realms/[id].ts
  app/pages/api/realms/pending.ts
  app/pages/custom-realm-dashboard.tsx
  app/prisma/schema.prisma
  app/services/realm.ts
  app/types/realm-profile.ts
  app/utils/github.ts
  app/utils/mailer.ts
  app/utils/terraform.ts
  app/utils/tf-custom-realm-template.mustache
  app/validators/create-realm.ts
  helm/webapp/migration.sql
Labels: enhancement

#139 chore: remove environment option from form
  app/__tests__/custom-realm-form.test.tsx
  app/__tests__/my-dashboard.test.tsx
  app/components/RealmForm.tsx
  app/page-partials/custom-realm-dashboard/CustomRealmTabs.tsx
  app/pages/api/realms.ts
  app/pages/custom-realm-form.tsx
  app/types/realm-profile.ts
  app/utils/mailer.ts
  app/validators/create-realm.ts
Labels: enhancement

#140 fix: promise completion in route
  app/pages/api/realms/[id].ts
  app/pages/api/realms/pending.ts
Labels: bug

#141 fix: typo on role name
  app/controllers/keycloak.ts
Labels: bug

#142 feat: ready to use email after terraform applies the realm and improved consistency for emails
  app/page-partials/my-dashboard/RealmURIs.tsx
  app/pages/api/realms/[id].ts
  app/pages/api/realms/pending.ts
  app/utils/helpers.ts
  app/utils/mailer.ts
Labels: enhancement

#143 feat: minor style tweaks for emails
  app/pages/api/realms.ts
  app/utils/mailer.ts
Labels: enhancement

#144 fix: fetch correct domains for realm uris
  app/page-partials/my-dashboard/RealmURIs.tsx
  app/pages/my-dashboard.tsx
Labels: bug

#146 feat: filter and sort realm table
  app/pages/api/realms.ts
  app/pages/custom-realm-dashboard.tsx
  app/pages/my-dashboard.tsx
  app/services/realm.ts
Labels: enhancement

#148 chore: use similar UI for realm name taken message
  app/components/RealmForm.tsx
  app/pages/api/realms.ts
  app/pages/custom-realm-form.tsx
Labels: enhancement

#147 feat: email for onboarding and offboarding team mems
  app/pages/api/realms.ts
  app/pages/api/realms/[id].ts
  app/public/offboard-realm-admin.png
  app/public/onboard-realm-admin.png
  app/utils/mailer.ts
Labels: enhancement

#149 chore: multiselect for filters
  app/__tests__/custom-realm-dashboard.test.tsx
  app/components/Badge.tsx
  app/page-partials/custom-realm-dashboard/CustomRealmTabs.tsx
  app/page-partials/my-dashboard/RealmTable.tsx
  app/pages/custom-realm-dashboard.tsx
Labels: enhancement

#151 chore: update email phrasing
  app/utils/mailer.ts
Labels: enhancement

#152 chore: change name filter button style
  app/pages/custom-realm-dashboard.tsx
Labels: enhancement

#153 chore: show archived requests in the admin dashboard
  app/pages/custom-realm-dashboard.tsx
Labels: enhancement
