Repository bcgov/sso-realm-registry, pull requests merged in 2024-01, with the labels that each got.

#155 chore: cc email
  app/utils/mailer.ts
Labels: enhancement

#157 fix: realm name validation
  app/components/RealmForm.tsx
  app/validators/create-realm.ts
Labels: bug

#158 feat: use password grant for connecting to keycloak
  app/.env.example
  app/controllers/keycloak.ts
  app/next.config.js
  app/utils/keycloak-core.ts
  helm/webapp/README.md
  helm/webapp/templates/deployment.yaml
Labels: bug

#159 chore: release
  app/.env.example
  app/components/RealmForm.tsx
  app/controllers/keycloak.ts
  app/layout/Layout.tsx
  app/next.config.js
  app/pages/index.tsx
  app/utils/helpers.ts
  app/utils/keycloak-core.ts
  app/utils/mailer.ts
  app/validators/create-realm.ts
  helm/webapp/README.md
  helm/webapp/templates/deployment.yaml
Labels: release:minor
