Repository bcgov/sso-realm-registry, pull requests merged in 2024-08, with the labels that each got.

#168 chore: reduce sandbox resources
  helm/webapp/values-c6af30-dev.yaml
Labels: enhancement

#171 chore: remove beta tag from realm reg
  app/layout/Layout.tsx
Labels: enhancement

#172 feat: use common table component from sso components
  app/__tests__/custom-realm-dashboard.test.tsx
  app/__tests__/my-dashboard.test.tsx
  app/components/ActionButton.tsx
  app/package.json
  app/page-partials/my-dashboard/RealmTable.tsx
  app/pages/custom-realm-dashboard.tsx
  app/yarn.lock
Labels: enhancement

#173 feat: add sso team email for all update notifications
  app/utils/mailer.ts
Labels: enhancement

#177 chore: change form field name
  app/__tests__/realm-edit.test.tsx
  app/components/RealmForm.tsx
Labels: enhancement

#180 chore: fix colours in realm reg text and links
  app/layout/BCSans.tsx
  app/layout/Layout.tsx
  app/pages/index.tsx
  app/styles/globals.css
Labels: enhancement

#183 feat: upgrade next to 14 and remove tf dependency
  .github/workflows/test.yml
  .tool-versions
  app/.babelrc
  app/.eslintrc.json
  app/Dockerfile
  app/__tests__/api/delete-realm.test.ts
  app/__tests__/api/update-realm.test.ts
  app/__tests__/custom-realm-dashboard.test.tsx
  app/__tests__/fixtures.ts
  app/controllers/keycloak.ts
  app/layout/Layout.tsx
  app/package.json
  app/pages/api/realms.ts
  app/pages/api/realms/[id]/index.ts
  app/pages/custom-realm-dashboard.tsx
  app/pages/index.tsx
  app/utils/helpers.ts
  app/utils/jwt.ts
  app/utils/keycloak-core.ts
  app/utils/mailer.ts
  app/utils/oidc.ts
  app/yarn.lock
Labels: enhancement, release:minor

#184 fix: build issues with nextjs 14
  app/.babelrc
  app/pages/_app.tsx
  app/pages/_document.tsx
  app/pages/custom-realm-dashboard.tsx
  app/yarn.lock
Labels: bug

#185 fix: refactor restore func to use kc admin api
  app/__tests__/api/delete-realm.test.ts
  app/__tests__/api/restore-realm.test.ts
  app/__tests__/api/update-realm.test.ts
  app/__tests__/api/utils/mocks.ts
  app/__tests__/my-dashboard.test.tsx
  app/controllers/keycloak.ts
  app/package.json
  app/pages/api/realms/[id]/index.ts
  app/pages/api/realms/[id]/restore.ts
  app/pages/api/realms/pending.ts
  app/pages/custom-realm-dashboard.tsx
  app/utils/keycloak-core.ts
  app/yarn.lock
Labels: enhancement

#186 fix: restore users during realm restoration
  app/pages/api/realms/[id]/restore.ts
Labels: enhancement
